version: "3"
services:
  web:
    image: my-flask-app:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mongo
  mongo:
    image: my-mongodb-image:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

    
